// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License MIT. See License.md in the repository root for more information.

// Ported from um\d3d12sdklayers.h in the Windows SDK for Windows 10.0.15063.0
// Original source is Copyright © Microsoft. All rights reserved.

namespace TerraFX.Interop.D3D12
{
    public enum D3D12_MESSAGE_ID
    {
        UNKNOWN = 0,

        STRING_FROM_APPLICATION = 1,

        CORRUPTED_THIS = 2,

        CORRUPTED_PARAMETER1 = 3,

        CORRUPTED_PARAMETER2 = 4,

        CORRUPTED_PARAMETER3 = 5,

        CORRUPTED_PARAMETER4 = 6,

        CORRUPTED_PARAMETER5 = 7,

        CORRUPTED_PARAMETER6 = 8,

        CORRUPTED_PARAMETER7 = 9,

        CORRUPTED_PARAMETER8 = 10,

        CORRUPTED_PARAMETER9 = 11,

        CORRUPTED_PARAMETER10 = 12,

        CORRUPTED_PARAMETER11 = 13,

        CORRUPTED_PARAMETER12 = 14,

        CORRUPTED_PARAMETER13 = 15,

        CORRUPTED_PARAMETER14 = 16,

        CORRUPTED_PARAMETER15 = 17,

        CORRUPTED_MULTITHREADING = 18,

        MESSAGE_REPORTING_OUTOFMEMORY = 19,

        GETPRIVATEDATA_MOREDATA = 20,

        SETPRIVATEDATA_INVALIDFREEDATA = 21,

        SETPRIVATEDATA_INVALIDIUNKNOWN = 22,

        SETPRIVATEDATA_INVALIDFLAGS = 23,

        SETPRIVATEDATA_CHANGINGPARAMS = 24,

        SETPRIVATEDATA_OUTOFMEMORY = 25,

        CREATESHADERRESOURCEVIEW_UNRECOGNIZEDFORMAT = 26,

        CREATESHADERRESOURCEVIEW_INVALIDDESC = 27,

        CREATESHADERRESOURCEVIEW_INVALIDFORMAT = 28,

        CREATESHADERRESOURCEVIEW_INVALIDVIDEOPLANESLICE = 29,

        CREATESHADERRESOURCEVIEW_INVALIDPLANESLICE = 30,

        CREATESHADERRESOURCEVIEW_INVALIDDIMENSIONS = 31,

        CREATESHADERRESOURCEVIEW_INVALIDRESOURCE = 32,

        CREATESHADERRESOURCEVIEW_INVALIDARG_RETURN = 33,

        CREATESHADERRESOURCEVIEW_OUTOFMEMORY_RETURN = 34,

        CREATERENDERTARGETVIEW_UNRECOGNIZEDFORMAT = 35,

        CREATERENDERTARGETVIEW_UNSUPPORTEDFORMAT = 36,

        CREATERENDERTARGETVIEW_INVALIDDESC = 37,

        CREATERENDERTARGETVIEW_INVALIDFORMAT = 38,

        CREATERENDERTARGETVIEW_INVALIDVIDEOPLANESLICE = 39,

        CREATERENDERTARGETVIEW_INVALIDPLANESLICE = 40,

        CREATERENDERTARGETVIEW_INVALIDDIMENSIONS = 41,

        CREATERENDERTARGETVIEW_INVALIDRESOURCE = 42,

        CREATERENDERTARGETVIEW_INVALIDARG_RETURN = 43,

        CREATERENDERTARGETVIEW_OUTOFMEMORY_RETURN = 44,

        CREATEDEPTHSTENCILVIEW_UNRECOGNIZEDFORMAT = 45,

        CREATEDEPTHSTENCILVIEW_INVALIDDESC = 46,

        CREATEDEPTHSTENCILVIEW_INVALIDFORMAT = 47,

        CREATEDEPTHSTENCILVIEW_INVALIDDIMENSIONS = 48,

        CREATEDEPTHSTENCILVIEW_INVALIDRESOURCE = 49,

        CREATEDEPTHSTENCILVIEW_INVALIDARG_RETURN = 50,

        CREATEDEPTHSTENCILVIEW_OUTOFMEMORY_RETURN = 51,

        CREATEINPUTLAYOUT_OUTOFMEMORY = 52,

        CREATEINPUTLAYOUT_TOOMANYELEMENTS = 53,

        CREATEINPUTLAYOUT_INVALIDFORMAT = 54,

        CREATEINPUTLAYOUT_INCOMPATIBLEFORMAT = 55,

        CREATEINPUTLAYOUT_INVALIDSLOT = 56,

        CREATEINPUTLAYOUT_INVALIDINPUTSLOTCLASS = 57,

        CREATEINPUTLAYOUT_STEPRATESLOTCLASSMISMATCH = 58,

        CREATEINPUTLAYOUT_INVALIDSLOTCLASSCHANGE = 59,

        CREATEINPUTLAYOUT_INVALIDSTEPRATECHANGE = 60,

        CREATEINPUTLAYOUT_INVALIDALIGNMENT = 61,

        CREATEINPUTLAYOUT_DUPLICATESEMANTIC = 62,

        CREATEINPUTLAYOUT_UNPARSEABLEINPUTSIGNATURE = 63,

        CREATEINPUTLAYOUT_NULLSEMANTIC = 64,

        CREATEINPUTLAYOUT_MISSINGELEMENT = 65,

        CREATEVERTEXSHADER_OUTOFMEMORY = 66,

        CREATEVERTEXSHADER_INVALIDSHADERBYTECODE = 67,

        CREATEVERTEXSHADER_INVALIDSHADERTYPE = 68,

        CREATEGEOMETRYSHADER_OUTOFMEMORY = 69,

        CREATEGEOMETRYSHADER_INVALIDSHADERBYTECODE = 70,

        CREATEGEOMETRYSHADER_INVALIDSHADERTYPE = 71,

        CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_OUTOFMEMORY = 72,

        CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDSHADERBYTECODE = 73,

        CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDSHADERTYPE = 74,

        CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDNUMENTRIES = 75,

        CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_OUTPUTSTREAMSTRIDEUNUSED = 76,

        CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_UNEXPECTEDDECL = 77,

        CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_EXPECTEDDECL = 78,

        CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_OUTPUTSLOT0EXPECTED = 79,

        CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDOUTPUTSLOT = 80,

        CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_ONLYONEELEMENTPERSLOT = 81,

        CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDCOMPONENTCOUNT = 82,

        CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDSTARTCOMPONENTANDCOMPONENTCOUNT = 83,

        CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDGAPDEFINITION = 84,

        CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_REPEATEDOUTPUT = 85,

        CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDOUTPUTSTREAMSTRIDE = 86,

        CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_MISSINGSEMANTIC = 87,

        CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_MASKMISMATCH = 88,

        CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_CANTHAVEONLYGAPS = 89,

        CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_DECLTOOCOMPLEX = 90,

        CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_MISSINGOUTPUTSIGNATURE = 91,

        CREATEPIXELSHADER_OUTOFMEMORY = 92,

        CREATEPIXELSHADER_INVALIDSHADERBYTECODE = 93,

        CREATEPIXELSHADER_INVALIDSHADERTYPE = 94,

        CREATERASTERIZERSTATE_INVALIDFILLMODE = 95,

        CREATERASTERIZERSTATE_INVALIDCULLMODE = 96,

        CREATERASTERIZERSTATE_INVALIDDEPTHBIASCLAMP = 97,

        CREATERASTERIZERSTATE_INVALIDSLOPESCALEDDEPTHBIAS = 98,

        CREATERASTERIZERSTATE_NULLDESC = 99,

        CREATEDEPTHSTENCILSTATE_INVALIDDEPTHWRITEMASK = 100,

        CREATEDEPTHSTENCILSTATE_INVALIDDEPTHFUNC = 101,

        CREATEDEPTHSTENCILSTATE_INVALIDFRONTFACESTENCILFAILOP = 102,

        CREATEDEPTHSTENCILSTATE_INVALIDFRONTFACESTENCILZFAILOP = 103,

        CREATEDEPTHSTENCILSTATE_INVALIDFRONTFACESTENCILPASSOP = 104,

        CREATEDEPTHSTENCILSTATE_INVALIDFRONTFACESTENCILFUNC = 105,

        CREATEDEPTHSTENCILSTATE_INVALIDBACKFACESTENCILFAILOP = 106,

        CREATEDEPTHSTENCILSTATE_INVALIDBACKFACESTENCILZFAILOP = 107,

        CREATEDEPTHSTENCILSTATE_INVALIDBACKFACESTENCILPASSOP = 108,

        CREATEDEPTHSTENCILSTATE_INVALIDBACKFACESTENCILFUNC = 109,

        CREATEDEPTHSTENCILSTATE_NULLDESC = 110,

        CREATEBLENDSTATE_INVALIDSRCBLEND = 111,

        CREATEBLENDSTATE_INVALIDDESTBLEND = 112,

        CREATEBLENDSTATE_INVALIDBLENDOP = 113,

        CREATEBLENDSTATE_INVALIDSRCBLENDALPHA = 114,

        CREATEBLENDSTATE_INVALIDDESTBLENDALPHA = 115,

        CREATEBLENDSTATE_INVALIDBLENDOPALPHA = 116,

        CREATEBLENDSTATE_INVALIDRENDERTARGETWRITEMASK = 117,

        CREATEBLENDSTATE_NULLDESC = 118,

        CREATESAMPLERSTATE_INVALIDFILTER = 119,

        CREATESAMPLERSTATE_INVALIDADDRESSU = 120,

        CREATESAMPLERSTATE_INVALIDADDRESSV = 121,

        CREATESAMPLERSTATE_INVALIDADDRESSW = 122,

        CREATESAMPLERSTATE_INVALIDMIPLODBIAS = 123,

        CREATESAMPLERSTATE_INVALIDMAXANISOTROPY = 124,

        CREATESAMPLERSTATE_INVALIDCOMPARISONFUNC = 125,

        CREATESAMPLERSTATE_INVALIDMINLOD = 126,

        CREATESAMPLERSTATE_INVALIDMAXLOD = 127,

        CREATESAMPLERSTATE_NULLDESC = 128,

        DEVICE_IASETPRIMITIVETOPOLOGY_TOPOLOGY_UNRECOGNIZED = 129,

        DEVICE_IASETPRIMITIVETOPOLOGY_TOPOLOGY_UNDEFINED = 130,

        DEVICE_RSSETVIEWPORTS_INVALIDVIEWPORT = 131,

        DEVICE_RSSETSCISSORRECTS_INVALIDSCISSOR = 132,

        CLEARRENDERTARGETVIEW_DENORMFLUSH = 133,

        CLEARDEPTHSTENCILVIEW_DENORMFLUSH = 134,

        CLEARDEPTHSTENCILVIEW_INVALID = 135,

        COPYRESOURCE_INVALIDSOURCE = 136,

        COPYRESOURCE_INVALIDDESTINATIONSTATE = 137,

        COPYRESOURCE_INVALIDSOURCESTATE = 138,

        UPDATESUBRESOURCE_INVALIDDESTINATIONSUBRESOURCE = 139,

        UPDATESUBRESOURCE_INVALIDDESTINATIONBOX = 140,

        UPDATESUBRESOURCE_INVALIDDESTINATIONSTATE = 141,

        DEVICE_RESOLVESUBRESOURCE_DESTINATION_INVALID = 142,

        DEVICE_RESOLVESUBRESOURCE_DESTINATION_SUBRESOURCE_INVALID = 143,

        DEVICE_RESOLVESUBRESOURCE_SOURCE_INVALID = 144,

        DEVICE_RESOLVESUBRESOURCE_SOURCE_SUBRESOURCE_INVALID = 145,

        DEVICE_RESOLVESUBRESOURCE_FORMAT_INVALID = 146,

        BUFFER_MAP_INVALIDMAPTYPE = 147,

        BUFFER_MAP_INVALIDFLAGS = 148,

        BUFFER_MAP_ALREADYMAPPED = 149,

        BUFFER_MAP_DEVICEREMOVED_RETURN = 150,

        BUFFER_UNMAP_NOTMAPPED = 151,

        TEXTURE1D_MAP_INVALIDMAPTYPE = 152,

        TEXTURE1D_MAP_INVALIDSUBRESOURCE = 153,

        TEXTURE1D_MAP_INVALIDFLAGS = 154,

        TEXTURE1D_MAP_ALREADYMAPPED = 155,

        TEXTURE1D_MAP_DEVICEREMOVED_RETURN = 156,

        TEXTURE1D_UNMAP_INVALIDSUBRESOURCE = 157,

        TEXTURE1D_UNMAP_NOTMAPPED = 158,

        TEXTURE2D_MAP_INVALIDMAPTYPE = 159,

        TEXTURE2D_MAP_INVALIDSUBRESOURCE = 160,

        TEXTURE2D_MAP_INVALIDFLAGS = 161,

        TEXTURE2D_MAP_ALREADYMAPPED = 162,

        TEXTURE2D_MAP_DEVICEREMOVED_RETURN = 163,

        TEXTURE2D_UNMAP_INVALIDSUBRESOURCE = 164,

        TEXTURE2D_UNMAP_NOTMAPPED = 165,

        TEXTURE3D_MAP_INVALIDMAPTYPE = 166,

        TEXTURE3D_MAP_INVALIDSUBRESOURCE = 167,

        TEXTURE3D_MAP_INVALIDFLAGS = 168,

        TEXTURE3D_MAP_ALREADYMAPPED = 169,

        TEXTURE3D_MAP_DEVICEREMOVED_RETURN = 170,

        TEXTURE3D_UNMAP_INVALIDSUBRESOURCE = 171,

        TEXTURE3D_UNMAP_NOTMAPPED = 172,

        CHECKFORMATSUPPORT_FORMAT_DEPRECATED = 173,

        CHECKMULTISAMPLEQUALITYLEVELS_FORMAT_DEPRECATED = 174,

        SETEXCEPTIONMODE_UNRECOGNIZEDFLAGS = 175,

        SETEXCEPTIONMODE_INVALIDARG_RETURN = 176,

        SETEXCEPTIONMODE_DEVICEREMOVED_RETURN = 177,

        REF_SIMULATING_INFINITELY_FAST_HARDWARE = 178,

        REF_THREADING_MODE = 179,

        REF_UMDRIVER_EXCEPTION = 180,

        REF_KMDRIVER_EXCEPTION = 181,

        REF_HARDWARE_EXCEPTION = 182,

        REF_ACCESSING_INDEXABLE_TEMP_OUT_OF_RANGE = 183,

        REF_PROBLEM_PARSING_SHADER = 184,

        REF_OUT_OF_MEMORY = 185,

        REF_INFO = 186,

        DEVICE_DRAW_VERTEXPOS_OVERFLOW = 187,

        DEVICE_DRAWINDEXED_INDEXPOS_OVERFLOW = 188,

        DEVICE_DRAWINSTANCED_VERTEXPOS_OVERFLOW = 189,

        DEVICE_DRAWINSTANCED_INSTANCEPOS_OVERFLOW = 190,

        DEVICE_DRAWINDEXEDINSTANCED_INSTANCEPOS_OVERFLOW = 191,

        DEVICE_DRAWINDEXEDINSTANCED_INDEXPOS_OVERFLOW = 192,

        DEVICE_DRAW_VERTEX_SHADER_NOT_SET = 193,

        DEVICE_SHADER_LINKAGE_SEMANTICNAME_NOT_FOUND = 194,

        DEVICE_SHADER_LINKAGE_REGISTERINDEX = 195,

        DEVICE_SHADER_LINKAGE_COMPONENTTYPE = 196,

        DEVICE_SHADER_LINKAGE_REGISTERMASK = 197,

        DEVICE_SHADER_LINKAGE_SYSTEMVALUE = 198,

        DEVICE_SHADER_LINKAGE_NEVERWRITTEN_ALWAYSREADS = 199,

        COMMAND_LIST_DRAW_ROOT_SIGNATURE_NOT_SET = 200,

        COMMAND_LIST_DRAW_ROOT_SIGNATURE_MISMATCH = 201,

        COMMAND_LIST_DRAW_VERTEX_BUFFER_NOT_SET = 202,

        COMMAND_LIST_DRAW_INPUTLAYOUT_NOT_SET = 203,

        COMMAND_LIST_DRAW_CONSTANT_BUFFER_NOT_SET = 204,

        COMMAND_LIST_DRAW_CONSTANT_BUFFER_TOO_SMALL = 205,

        COMMAND_LIST_DRAW_SAMPLER_NOT_SET = 206,

        COMMAND_LIST_DRAW_SHADERRESOURCEVIEW_NOT_SET = 207,

        COMMAND_LIST_DRAW_VIEW_DIMENSION_MISMATCH = 208,

        COMMAND_LIST_DRAW_VERTEX_BUFFER_STRIDE_TOO_SMALL = 209,

        COMMAND_LIST_DRAW_VERTEX_BUFFER_TOO_SMALL = 210,

        COMMAND_LIST_DRAW_INDEX_BUFFER_NOT_SET = 211,

        COMMAND_LIST_DRAW_INDEX_BUFFER_FORMAT_INVALID = 212,

        COMMAND_LIST_DRAW_INDEX_BUFFER_TOO_SMALL = 213,

        COMMAND_LIST_DRAW_GS_INPUT_PRIMITIVE_MISMATCH = 214,

        COMMAND_LIST_DRAW_RESOURCE_RETURN_TYPE_MISMATCH = 215,

        COMMAND_LIST_DRAW_POSITION_NOT_PRESENT = 216,

        COMMAND_LIST_DRAW_OUTPUT_STREAM_NOT_SET = 217,

        COMMAND_LIST_DRAW_BOUND_RESOURCE_MAPPED = 218,

        COMMAND_LIST_DRAW_INVALID_PRIMITIVETOPOLOGY = 219,

        COMMAND_LIST_DRAW_VERTEX_OFFSET_UNALIGNED = 220,

        COMMAND_LIST_DRAW_VERTEX_STRIDE_UNALIGNED = 221,

        COMMAND_LIST_DRAW_INDEX_OFFSET_UNALIGNED = 222,

        COMMAND_LIST_DRAW_OUTPUT_STREAM_OFFSET_UNALIGNED = 223,

        COMMAND_LIST_DRAW_RESOURCE_FORMAT_LD_UNSUPPORTED = 224,

        COMMAND_LIST_DRAW_RESOURCE_FORMAT_SAMPLE_UNSUPPORTED = 225,

        COMMAND_LIST_DRAW_RESOURCE_FORMAT_SAMPLE_C_UNSUPPORTED = 226,

        COMMAND_LIST_DRAW_RESOURCE_MULTISAMPLE_UNSUPPORTED = 227,

        COMMAND_LIST_DRAW_SO_TARGETS_BOUND_WITHOUT_SOURCE = 228,

        COMMAND_LIST_DRAW_SO_STRIDE_LARGER_THAN_BUFFER = 229,

        COMMAND_LIST_DRAW_OM_RENDER_TARGET_DOES_NOT_SUPPORT_BLENDING = 230,

        COMMAND_LIST_DRAW_OM_DUAL_SOURCE_BLENDING_CAN_ONLY_HAVE_RENDER_TARGET_0 = 231,

        DEVICE_REMOVAL_PROCESS_AT_FAULT = 232,

        DEVICE_REMOVAL_PROCESS_POSSIBLY_AT_FAULT = 233,

        DEVICE_REMOVAL_PROCESS_NOT_AT_FAULT = 234,

        DEVICE_OPEN_SHARED_RESOURCE_INVALIDARG_RETURN = 235,

        DEVICE_OPEN_SHARED_RESOURCE_OUTOFMEMORY_RETURN = 236,

        DEVICE_OPEN_SHARED_RESOURCE_BADINTERFACE_RETURN = 237,

        DEVICE_DRAW_VIEWPORT_NOT_SET = 238,

        CREATEINPUTLAYOUT_TRAILING_DIGIT_IN_SEMANTIC = 239,

        CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_TRAILING_DIGIT_IN_SEMANTIC = 240,

        DEVICE_RSSETVIEWPORTS_DENORMFLUSH = 241,

        OMSETRENDERTARGETS_INVALIDVIEW = 242,

        DEVICE_SETTEXTFILTERSIZE_INVALIDDIMENSIONS = 243,

        DEVICE_DRAW_SAMPLER_MISMATCH = 244,

        CREATEINPUTLAYOUT_TYPE_MISMATCH = 245,

        BLENDSTATE_GETDESC_LEGACY = 246,

        SHADERRESOURCEVIEW_GETDESC_LEGACY = 247,

        DEVICE_DRAW_PS_OUTPUT_TYPE_MISMATCH = 248,

        DEVICE_DRAW_RESOURCE_FORMAT_GATHER_UNSUPPORTED = 249,

        DEVICE_DRAW_INVALID_USE_OF_CENTER_MULTISAMPLE_PATTERN = 250,

        DEVICE_IASETVERTEXBUFFERS_STRIDE_TOO_LARGE = 251,

        DEVICE_IASETVERTEXBUFFERS_INVALIDRANGE = 252,

        CREATEINPUTLAYOUT_EMPTY_LAYOUT = 253,

        DEVICE_DRAW_RESOURCE_SAMPLE_COUNT_MISMATCH = 254,

        LIVE_OBJECT_SUMMARY = 255,

        LIVE_BUFFER = 256,

        LIVE_TEXTURE1D = 257,

        LIVE_TEXTURE2D = 258,

        LIVE_TEXTURE3D = 259,

        LIVE_SHADERRESOURCEVIEW = 260,

        LIVE_RENDERTARGETVIEW = 261,

        LIVE_DEPTHSTENCILVIEW = 262,

        LIVE_VERTEXSHADER = 263,

        LIVE_GEOMETRYSHADER = 264,

        LIVE_PIXELSHADER = 265,

        LIVE_INPUTLAYOUT = 266,

        LIVE_SAMPLER = 267,

        LIVE_BLENDSTATE = 268,

        LIVE_DEPTHSTENCILSTATE = 269,

        LIVE_RASTERIZERSTATE = 270,

        LIVE_QUERY = 271,

        LIVE_PREDICATE = 272,

        LIVE_COUNTER = 273,

        LIVE_DEVICE = 274,

        LIVE_SWAPCHAIN = 275,

        CREATEDEPTHSTENCILVIEW_INVALIDFLAGS = 276,

        CREATEVERTEXSHADER_INVALIDCLASSLINKAGE = 277,

        CREATEGEOMETRYSHADER_INVALIDCLASSLINKAGE = 278,

        CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDNUMSTREAMS = 279,

        CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDSTREAMTORASTERIZER = 280,

        CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_UNEXPECTEDSTREAMS = 281,

        CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDCLASSLINKAGE = 282,

        CREATEPIXELSHADER_INVALIDCLASSLINKAGE = 283,

        CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDSTREAM = 284,

        CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_UNEXPECTEDENTRIES = 285,

        CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_UNEXPECTEDSTRIDES = 286,

        CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDNUMSTRIDES = 287,

        CREATEHULLSHADER_INVALIDCALL = 288,

        CREATEHULLSHADER_OUTOFMEMORY = 289,

        CREATEHULLSHADER_INVALIDSHADERBYTECODE = 290,

        CREATEHULLSHADER_INVALIDSHADERTYPE = 291,

        CREATEHULLSHADER_INVALIDCLASSLINKAGE = 292,

        CREATEDOMAINSHADER_INVALIDCALL = 293,

        CREATEDOMAINSHADER_OUTOFMEMORY = 294,

        CREATEDOMAINSHADER_INVALIDSHADERBYTECODE = 295,

        CREATEDOMAINSHADER_INVALIDSHADERTYPE = 296,

        CREATEDOMAINSHADER_INVALIDCLASSLINKAGE = 297,

        DEVICE_DRAW_HS_XOR_DS_MISMATCH = 298,

        DEVICE_DRAWINDIRECT_INVALID_ARG_BUFFER = 299,

        DEVICE_DRAWINDIRECT_OFFSET_UNALIGNED = 300,

        DEVICE_DRAWINDIRECT_OFFSET_OVERFLOW = 301,

        RESOURCE_MAP_INVALIDMAPTYPE = 302,

        RESOURCE_MAP_INVALIDSUBRESOURCE = 303,

        RESOURCE_MAP_INVALIDFLAGS = 304,

        RESOURCE_MAP_ALREADYMAPPED = 305,

        RESOURCE_MAP_DEVICEREMOVED_RETURN = 306,

        RESOURCE_MAP_OUTOFMEMORY_RETURN = 307,

        RESOURCE_MAP_WITHOUT_INITIAL_DISCARD = 308,

        RESOURCE_UNMAP_INVALIDSUBRESOURCE = 309,

        RESOURCE_UNMAP_NOTMAPPED = 310,

        DEVICE_DRAW_RASTERIZING_CONTROL_POINTS = 311,

        DEVICE_IASETPRIMITIVETOPOLOGY_TOPOLOGY_UNSUPPORTED = 312,

        DEVICE_DRAW_HS_DS_SIGNATURE_MISMATCH = 313,

        DEVICE_DRAW_HULL_SHADER_INPUT_TOPOLOGY_MISMATCH = 314,

        DEVICE_DRAW_HS_DS_CONTROL_POINT_COUNT_MISMATCH = 315,

        DEVICE_DRAW_HS_DS_TESSELLATOR_DOMAIN_MISMATCH = 316,

        DEVICE_CHECKFEATURESUPPORT_UNRECOGNIZED_FEATURE = 317,

        DEVICE_CHECKFEATURESUPPORT_MISMATCHED_DATA_SIZE = 318,

        DEVICE_CHECKFEATURESUPPORT_INVALIDARG_RETURN = 319,

        CREATECOMPUTESHADER_INVALIDCALL = 320,

        CREATECOMPUTESHADER_OUTOFMEMORY = 321,

        CREATECOMPUTESHADER_INVALIDSHADERBYTECODE = 322,

        CREATECOMPUTESHADER_INVALIDCLASSLINKAGE = 323,

        DEVICE_CSSETSHADERRESOURCES_VIEWS_EMPTY = 324,

        CSSETCONSTANTBUFFERS_INVALIDBUFFER = 325,

        DEVICE_CSSETCONSTANTBUFFERS_BUFFERS_EMPTY = 326,

        DEVICE_CSSETSAMPLERS_SAMPLERS_EMPTY = 327,

        DEVICE_CSGETSHADERRESOURCES_VIEWS_EMPTY = 328,

        DEVICE_CSGETCONSTANTBUFFERS_BUFFERS_EMPTY = 329,

        DEVICE_CSGETSAMPLERS_SAMPLERS_EMPTY = 330,

        DEVICE_CREATEVERTEXSHADER_DOUBLEFLOATOPSNOTSUPPORTED = 331,

        DEVICE_CREATEHULLSHADER_DOUBLEFLOATOPSNOTSUPPORTED = 332,

        DEVICE_CREATEDOMAINSHADER_DOUBLEFLOATOPSNOTSUPPORTED = 333,

        DEVICE_CREATEGEOMETRYSHADER_DOUBLEFLOATOPSNOTSUPPORTED = 334,

        DEVICE_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_DOUBLEFLOATOPSNOTSUPPORTED = 335,

        DEVICE_CREATEPIXELSHADER_DOUBLEFLOATOPSNOTSUPPORTED = 336,

        DEVICE_CREATECOMPUTESHADER_DOUBLEFLOATOPSNOTSUPPORTED = 337,

        CREATEBUFFER_INVALIDSTRUCTURESTRIDE = 338,

        CREATESHADERRESOURCEVIEW_INVALIDFLAGS = 339,

        CREATEUNORDEREDACCESSVIEW_INVALIDRESOURCE = 340,

        CREATEUNORDEREDACCESSVIEW_INVALIDDESC = 341,

        CREATEUNORDEREDACCESSVIEW_INVALIDFORMAT = 342,

        CREATEUNORDEREDACCESSVIEW_INVALIDVIDEOPLANESLICE = 343,

        CREATEUNORDEREDACCESSVIEW_INVALIDPLANESLICE = 344,

        CREATEUNORDEREDACCESSVIEW_INVALIDDIMENSIONS = 345,

        CREATEUNORDEREDACCESSVIEW_UNRECOGNIZEDFORMAT = 346,

        DEVICE_OMSETRENDERTARGETSANDUNORDEREDACCESSVIEWS_OVERLAPPING_OLD_SLOTS = 347,

        DEVICE_OMSETRENDERTARGETSANDUNORDEREDACCESSVIEWS_NO_OP = 348,

        CREATEUNORDEREDACCESSVIEW_INVALIDARG_RETURN = 349,

        CREATEUNORDEREDACCESSVIEW_OUTOFMEMORY_RETURN = 350,

        CLEARUNORDEREDACCESSVIEW_DENORMFLUSH = 351,

        DEVICE_CSSETUNORDEREDACCESSS_VIEWS_EMPTY = 352,

        DEVICE_CSGETUNORDEREDACCESSS_VIEWS_EMPTY = 353,

        CREATEUNORDEREDACCESSVIEW_INVALIDFLAGS = 354,

        DEVICE_DISPATCHINDIRECT_INVALID_ARG_BUFFER = 355,

        DEVICE_DISPATCHINDIRECT_OFFSET_UNALIGNED = 356,

        DEVICE_DISPATCHINDIRECT_OFFSET_OVERFLOW = 357,

        CLEARDEPTHSTENCILVIEW_DEPTH_READONLY = 358,

        CLEARDEPTHSTENCILVIEW_STENCIL_READONLY = 359,

        CHECKFEATURESUPPORT_FORMAT_DEPRECATED = 360,

        DEVICE_UNORDEREDACCESSVIEW_RETURN_TYPE_MISMATCH = 361,

        DEVICE_UNORDEREDACCESSVIEW_NOT_SET = 362,

        DEVICE_DRAW_UNORDEREDACCESSVIEW_RENDERTARGETVIEW_OVERLAP = 363,

        DEVICE_UNORDEREDACCESSVIEW_DIMENSION_MISMATCH = 364,

        DEVICE_UNORDEREDACCESSVIEW_APPEND_UNSUPPORTED = 365,

        DEVICE_UNORDEREDACCESSVIEW_ATOMICS_UNSUPPORTED = 366,

        DEVICE_UNORDEREDACCESSVIEW_STRUCTURE_STRIDE_MISMATCH = 367,

        DEVICE_UNORDEREDACCESSVIEW_BUFFER_TYPE_MISMATCH = 368,

        DEVICE_UNORDEREDACCESSVIEW_RAW_UNSUPPORTED = 369,

        DEVICE_UNORDEREDACCESSVIEW_FORMAT_LD_UNSUPPORTED = 370,

        DEVICE_UNORDEREDACCESSVIEW_FORMAT_STORE_UNSUPPORTED = 371,

        DEVICE_UNORDEREDACCESSVIEW_ATOMIC_ADD_UNSUPPORTED = 372,

        DEVICE_UNORDEREDACCESSVIEW_ATOMIC_BITWISE_OPS_UNSUPPORTED = 373,

        DEVICE_UNORDEREDACCESSVIEW_ATOMIC_CMPSTORE_CMPEXCHANGE_UNSUPPORTED = 374,

        DEVICE_UNORDEREDACCESSVIEW_ATOMIC_EXCHANGE_UNSUPPORTED = 375,

        DEVICE_UNORDEREDACCESSVIEW_ATOMIC_SIGNED_MINMAX_UNSUPPORTED = 376,

        DEVICE_UNORDEREDACCESSVIEW_ATOMIC_UNSIGNED_MINMAX_UNSUPPORTED = 377,

        DEVICE_DISPATCH_BOUND_RESOURCE_MAPPED = 378,

        DEVICE_DISPATCH_THREADGROUPCOUNT_OVERFLOW = 379,

        DEVICE_DISPATCH_THREADGROUPCOUNT_ZERO = 380,

        DEVICE_SHADERRESOURCEVIEW_STRUCTURE_STRIDE_MISMATCH = 381,

        DEVICE_SHADERRESOURCEVIEW_BUFFER_TYPE_MISMATCH = 382,

        DEVICE_SHADERRESOURCEVIEW_RAW_UNSUPPORTED = 383,

        DEVICE_DISPATCH_UNSUPPORTED = 384,

        DEVICE_DISPATCHINDIRECT_UNSUPPORTED = 385,

        COPYSTRUCTURECOUNT_INVALIDOFFSET = 386,

        COPYSTRUCTURECOUNT_LARGEOFFSET = 387,

        COPYSTRUCTURECOUNT_INVALIDDESTINATIONSTATE = 388,

        COPYSTRUCTURECOUNT_INVALIDSOURCESTATE = 389,

        CHECKFORMATSUPPORT_FORMAT_NOT_SUPPORTED = 390,

        CLEARUNORDEREDACCESSVIEWFLOAT_INVALIDFORMAT = 391,

        DEVICE_UNORDEREDACCESSVIEW_COUNTER_UNSUPPORTED = 392,

        DEVICE_DRAW_PIXEL_SHADER_WITHOUT_RTV_OR_DSV = 393,

        SHADER_ABORT = 394,

        SHADER_MESSAGE = 395,

        SHADER_ERROR = 396,

        OFFERRESOURCES_INVALIDRESOURCE = 397,

        ENQUEUESETEVENT_INVALIDARG_RETURN = 398,

        ENQUEUESETEVENT_OUTOFMEMORY_RETURN = 399,

        ENQUEUESETEVENT_ACCESSDENIED_RETURN = 400,

        CREATERASTERIZERSTATE_INVALIDFORCEDSAMPLECOUNT = 401,

        DEVICE_DRAW_INVALID_USE_OF_FORCED_SAMPLE_COUNT = 402,

        CREATEBLENDSTATE_INVALIDLOGICOPS = 403,

        CREATESHADERRESOURCEVIEW_INVALIDARRAYWITHDECODER = 404,

        CREATEUNORDEREDACCESSVIEW_INVALIDARRAYWITHDECODER = 405,

        CREATERENDERTARGETVIEW_INVALIDARRAYWITHDECODER = 406,

        DEVICE_LOCKEDOUT_INTERFACE = 407,

        OFFERRESOURCES_INVALIDPRIORITY = 408,

        DEVICE_CLEARVIEW_INVALIDVIEW = 409,

        DEVICE_CREATEVERTEXSHADER_DOUBLEEXTENSIONSNOTSUPPORTED = 410,

        DEVICE_CREATEVERTEXSHADER_SHADEREXTENSIONSNOTSUPPORTED = 411,

        DEVICE_CREATEHULLSHADER_DOUBLEEXTENSIONSNOTSUPPORTED = 412,

        DEVICE_CREATEHULLSHADER_SHADEREXTENSIONSNOTSUPPORTED = 413,

        DEVICE_CREATEDOMAINSHADER_DOUBLEEXTENSIONSNOTSUPPORTED = 414,

        DEVICE_CREATEDOMAINSHADER_SHADEREXTENSIONSNOTSUPPORTED = 415,

        DEVICE_CREATEGEOMETRYSHADER_DOUBLEEXTENSIONSNOTSUPPORTED = 416,

        DEVICE_CREATEGEOMETRYSHADER_SHADEREXTENSIONSNOTSUPPORTED = 417,

        DEVICE_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_DOUBLEEXTENSIONSNOTSUPPORTED = 418,

        DEVICE_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_SHADEREXTENSIONSNOTSUPPORTED = 419,

        DEVICE_CREATEPIXELSHADER_DOUBLEEXTENSIONSNOTSUPPORTED = 420,

        DEVICE_CREATEPIXELSHADER_SHADEREXTENSIONSNOTSUPPORTED = 421,

        DEVICE_CREATECOMPUTESHADER_DOUBLEEXTENSIONSNOTSUPPORTED = 422,

        DEVICE_CREATECOMPUTESHADER_SHADEREXTENSIONSNOTSUPPORTED = 423,

        DEVICE_SHADER_LINKAGE_MINPRECISION = 424,

        DEVICE_CREATEVERTEXSHADER_UAVSNOTSUPPORTED = 425,

        DEVICE_CREATEHULLSHADER_UAVSNOTSUPPORTED = 426,

        DEVICE_CREATEDOMAINSHADER_UAVSNOTSUPPORTED = 427,

        DEVICE_CREATEGEOMETRYSHADER_UAVSNOTSUPPORTED = 428,

        DEVICE_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_UAVSNOTSUPPORTED = 429,

        DEVICE_CREATEPIXELSHADER_UAVSNOTSUPPORTED = 430,

        DEVICE_CREATECOMPUTESHADER_UAVSNOTSUPPORTED = 431,

        DEVICE_OMSETRENDERTARGETSANDUNORDEREDACCESSVIEWS_INVALIDOFFSET = 432,

        DEVICE_OMSETRENDERTARGETSANDUNORDEREDACCESSVIEWS_TOOMANYVIEWS = 433,

        DEVICE_CLEARVIEW_NOTSUPPORTED = 434,

        SWAPDEVICECONTEXTSTATE_NOTSUPPORTED = 435,

        UPDATESUBRESOURCE_PREFERUPDATESUBRESOURCE1 = 436,

        GETDC_INACCESSIBLE = 437,

        DEVICE_CLEARVIEW_INVALIDRECT = 438,

        DEVICE_DRAW_SAMPLE_MASK_IGNORED_ON_FL9 = 439,

        DEVICE_OPEN_SHARED_RESOURCE1_NOT_SUPPORTED = 440,

        DEVICE_OPEN_SHARED_RESOURCE_BY_NAME_NOT_SUPPORTED = 441,

        ENQUEUESETEVENT_NOT_SUPPORTED = 442,

        OFFERRELEASE_NOT_SUPPORTED = 443,

        OFFERRESOURCES_INACCESSIBLE = 444,

        CREATEVIDEOPROCESSORINPUTVIEW_INVALIDMSAA = 445,

        CREATEVIDEOPROCESSOROUTPUTVIEW_INVALIDMSAA = 446,

        DEVICE_CLEARVIEW_INVALIDSOURCERECT = 447,

        DEVICE_CLEARVIEW_EMPTYRECT = 448,

        UPDATESUBRESOURCE_EMPTYDESTBOX = 449,

        COPYSUBRESOURCEREGION_EMPTYSOURCEBOX = 450,

        DEVICE_DRAW_OM_RENDER_TARGET_DOES_NOT_SUPPORT_LOGIC_OPS = 451,

        DEVICE_DRAW_DEPTHSTENCILVIEW_NOT_SET = 452,

        DEVICE_DRAW_RENDERTARGETVIEW_NOT_SET = 453,

        DEVICE_DRAW_RENDERTARGETVIEW_NOT_SET_DUE_TO_FLIP_PRESENT = 454,

        DEVICE_UNORDEREDACCESSVIEW_NOT_SET_DUE_TO_FLIP_PRESENT = 455,

        GETDATAFORNEWHARDWAREKEY_NULLPARAM = 456,

        CHECKCRYPTOSESSIONSTATUS_NULLPARAM = 457,

        SETEVENTONHARDWARECONTENTPROTECTIONTILT_NULLPARAM = 458,

        GETVIDEODECODERCAPS_NULLPARAM = 459,

        GETVIDEODECODERCAPS_ZEROWIDTHHEIGHT = 460,

        CHECKVIDEODECODERDOWNSAMPLING_NULLPARAM = 461,

        CHECKVIDEODECODERDOWNSAMPLING_INVALIDCOLORSPACE = 462,

        CHECKVIDEODECODERDOWNSAMPLING_ZEROWIDTHHEIGHT = 463,

        VIDEODECODERENABLEDOWNSAMPLING_NULLPARAM = 464,

        VIDEODECODERENABLEDOWNSAMPLING_UNSUPPORTED = 465,

        VIDEODECODERUPDATEDOWNSAMPLING_NULLPARAM = 466,

        VIDEODECODERUPDATEDOWNSAMPLING_UNSUPPORTED = 467,

        CHECKVIDEOPROCESSORFORMATCONVERSION_NULLPARAM = 468,

        VIDEOPROCESSORSETOUTPUTCOLORSPACE1_NULLPARAM = 469,

        VIDEOPROCESSORGETOUTPUTCOLORSPACE1_NULLPARAM = 470,

        VIDEOPROCESSORSETSTREAMCOLORSPACE1_NULLPARAM = 471,

        VIDEOPROCESSORSETSTREAMCOLORSPACE1_INVALIDSTREAM = 472,

        VIDEOPROCESSORSETSTREAMMIRROR_NULLPARAM = 473,

        VIDEOPROCESSORSETSTREAMMIRROR_INVALIDSTREAM = 474,

        VIDEOPROCESSORSETSTREAMMIRROR_UNSUPPORTED = 475,

        VIDEOPROCESSORGETSTREAMCOLORSPACE1_NULLPARAM = 476,

        VIDEOPROCESSORGETSTREAMMIRROR_NULLPARAM = 477,

        RECOMMENDVIDEODECODERDOWNSAMPLING_NULLPARAM = 478,

        RECOMMENDVIDEODECODERDOWNSAMPLING_INVALIDCOLORSPACE = 479,

        RECOMMENDVIDEODECODERDOWNSAMPLING_ZEROWIDTHHEIGHT = 480,

        VIDEOPROCESSORSETOUTPUTSHADERUSAGE_NULLPARAM = 481,

        VIDEOPROCESSORGETOUTPUTSHADERUSAGE_NULLPARAM = 482,

        VIDEOPROCESSORGETBEHAVIORHINTS_NULLPARAM = 483,

        VIDEOPROCESSORGETBEHAVIORHINTS_INVALIDSTREAMCOUNT = 484,

        VIDEOPROCESSORGETBEHAVIORHINTS_TARGETRECT = 485,

        VIDEOPROCESSORGETBEHAVIORHINTS_INVALIDSOURCERECT = 486,

        VIDEOPROCESSORGETBEHAVIORHINTS_INVALIDDESTRECT = 487,

        CREATEBUFFER_INVALIDUSAGE = 488,

        CREATETEXTURE1D_INVALIDUSAGE = 489,

        CREATETEXTURE2D_INVALIDUSAGE = 490,

        CREATEINPUTLAYOUT_LEVEL9_STEPRATE_NOT_1 = 491,

        CREATEINPUTLAYOUT_LEVEL9_INSTANCING_NOT_SUPPORTED = 492,

        UPDATETILEMAPPINGS_INVALID_PARAMETER = 493,

        COPYTILEMAPPINGS_INVALID_PARAMETER = 494,

        COPYTILES_INVALID_PARAMETER = 495,

        NULL_TILE_MAPPING_ACCESS_WARNING = 496,

        NULL_TILE_MAPPING_ACCESS_ERROR = 497,

        DIRTY_TILE_MAPPING_ACCESS = 498,

        DUPLICATE_TILE_MAPPINGS_IN_COVERED_AREA = 499,

        TILE_MAPPINGS_IN_COVERED_AREA_DUPLICATED_OUTSIDE = 500,

        TILE_MAPPINGS_SHARED_BETWEEN_INCOMPATIBLE_RESOURCES = 501,

        TILE_MAPPINGS_SHARED_BETWEEN_INPUT_AND_OUTPUT = 502,

        CHECKMULTISAMPLEQUALITYLEVELS_INVALIDFLAGS = 503,

        GETRESOURCETILING_NONTILED_RESOURCE = 504,

        NEED_TO_CALL_TILEDRESOURCEBARRIER = 505,

        CREATEDEVICE_INVALIDARGS = 506,

        CREATEDEVICE_WARNING = 507,

        TILED_RESOURCE_TIER_1_BUFFER_TEXTURE_MISMATCH = 508,

        CREATE_CRYPTOSESSION = 509,

        CREATE_AUTHENTICATEDCHANNEL = 510,

        LIVE_CRYPTOSESSION = 511,

        LIVE_AUTHENTICATEDCHANNEL = 512,

        DESTROY_CRYPTOSESSION = 513,

        DESTROY_AUTHENTICATEDCHANNEL = 514,

        MAP_INVALID_SUBRESOURCE = 515,

        MAP_INVALID_TYPE = 516,

        MAP_UNSUPPORTED_TYPE = 517,

        UNMAP_INVALID_SUBRESOURCE = 518,

        RESOURCE_BARRIER_INVALID_TYPE = 519,

        RESOURCE_BARRIER_NULL_POINTER = 520,

        RESOURCE_BARRIER_INVALID_SUBRESOURCE = 521,

        RESOURCE_BARRIER_RESERVED_BITS = 522,

        RESOURCE_BARRIER_MISSING_BIND_FLAGS = 523,

        RESOURCE_BARRIER_MISMATCHING_MISC_FLAGS = 524,

        RESOURCE_BARRIER_MATCHING_STATES = 525,

        RESOURCE_BARRIER_INVALID_COMBINATION = 526,

        RESOURCE_BARRIER_BEFORE_AFTER_MISMATCH = 527,

        RESOURCE_BARRIER_INVALID_RESOURCE = 528,

        RESOURCE_BARRIER_SAMPLE_COUNT = 529,

        RESOURCE_BARRIER_INVALID_FLAGS = 530,

        RESOURCE_BARRIER_INVALID_COMBINED_FLAGS = 531,

        RESOURCE_BARRIER_INVALID_FLAGS_FOR_FORMAT = 532,

        RESOURCE_BARRIER_INVALID_SPLIT_BARRIER = 533,

        RESOURCE_BARRIER_UNMATCHED_END = 534,

        RESOURCE_BARRIER_UNMATCHED_BEGIN = 535,

        RESOURCE_BARRIER_INVALID_FLAG = 536,

        RESOURCE_BARRIER_INVALID_COMMAND_LIST_TYPE = 537,

        INVALID_SUBRESOURCE_STATE = 538,

        INEFFICIENT_PRESENT = 539,

        COMMAND_ALLOCATOR_CONTENTION = 540,

        COMMAND_ALLOCATOR_RESET = 541,

        COMMAND_ALLOCATOR_RESET_BUNDLE = 542,

        COMMAND_ALLOCATOR_CANNOT_RESET = 543,

        COMMAND_LIST_OPEN = 544,

        QUERY_STATE_MISMATCH = 545,

        INVALID_BUNDLE_API = 546,

        COMMAND_LIST_CLOSED = 547,

        COMMAND_LIST_CLOSED_WITH_INVALID_RESOURCE = 548,

        WRONG_COMMAND_ALLOCATOR_TYPE = 549,

        INVALID_INDIRECT_ARGUMENT_BUFFER = 550,

        COMPUTE_AND_GRAPHICS_PIPELINE = 551,

        COMMAND_ALLOCATOR_SYNC = 552,

        COMMAND_LIST_SYNC = 553,

        SET_DESCRIPTOR_HEAP_INVALID = 554,

        CREATE_QUEUE_IMAGE_NOT_SUPPORTED = 555,

        CREATE_COMMAND_ALLOCATOR_IMAGE_NOT_SUPPORTED = 556,

        CREATE_COMMANDQUEUE = 557,

        CREATE_COMMANDALLOCATOR = 558,

        CREATE_PIPELINESTATE = 559,

        CREATE_COMMANDLIST12 = 560,

        CREATE_IMAGECOMMANDLIST = 561,

        CREATE_RESOURCE = 562,

        CREATE_DESCRIPTORHEAP = 563,

        CREATE_ROOTSIGNATURE = 564,

        CREATE_LIBRARY = 565,

        CREATE_HEAP = 566,

        CREATE_MONITOREDFENCE = 567,

        CREATE_QUERYHEAP = 568,

        CREATE_COMMANDSIGNATURE = 569,

        LIVE_COMMANDQUEUE = 570,

        LIVE_COMMANDALLOCATOR = 571,

        LIVE_PIPELINESTATE = 572,

        LIVE_COMMANDLIST12 = 573,

        LIVE_IMAGECOMMANDLIST = 574,

        LIVE_RESOURCE = 575,

        LIVE_DESCRIPTORHEAP = 576,

        LIVE_ROOTSIGNATURE = 577,

        LIVE_LIBRARY = 578,

        LIVE_HEAP = 579,

        LIVE_MONITOREDFENCE = 580,

        LIVE_QUERYHEAP = 581,

        LIVE_COMMANDSIGNATURE = 582,

        DESTROY_COMMANDQUEUE = 583,

        DESTROY_COMMANDALLOCATOR = 584,

        DESTROY_PIPELINESTATE = 585,

        DESTROY_COMMANDLIST12 = 586,

        DESTROY_IMAGECOMMANDLIST = 587,

        DESTROY_RESOURCE = 588,

        DESTROY_DESCRIPTORHEAP = 589,

        DESTROY_ROOTSIGNATURE = 590,

        DESTROY_LIBRARY = 591,

        DESTROY_HEAP = 592,

        DESTROY_MONITOREDFENCE = 593,

        DESTROY_QUERYHEAP = 594,

        DESTROY_COMMANDSIGNATURE = 595,

        CREATERESOURCE_UNRECOGNIZEDHEAPTYPE = 596,

        CREATERESOURCE_INVALIDDIMENSIONS = 597,

        CREATERESOURCE_UNRECOGNIZEDMISCFLAGS = 598,

        CREATERESOURCE_INVALIDMISCFLAGS = 599,

        CREATERESOURCE_LARGEALLOCATION = 600,

        CREATERESOURCE_SMALLALLOCATION = 601,

        CREATERESOURCE_INVALIDARG_RETURN = 602,

        CREATERESOURCE_OUTOFMEMORY_RETURN = 603,

        CREATERESOURCE_INVALIDDESC = 604,

        CREATERESOURCE_INVALIDINITIALSTATE = 605,

        RESOURCE_HAS_PENDING_INITIAL_DATA = 606,

        POSSIBLY_INVALID_SUBRESOURCE_STATE = 607,

        INVALID_USE_OF_NON_RESIDENT_RESOURCE = 608,

        POSSIBLE_INVALID_USE_OF_NON_RESIDENT_RESOURCE = 609,

        BUNDLE_PIPELINE_STATE_MISMATCH = 610,

        PRIMITIVE_TOPOLOGY_MISMATCH_PIPELINE_STATE = 611,

        RENDER_TARGET_NUMBER_MISMATCH_PIPELINE_STATE = 612,

        RENDER_TARGET_FORMAT_MISMATCH_PIPELINE_STATE = 613,

        RENDER_TARGET_SAMPLE_DESC_MISMATCH_PIPELINE_STATE = 614,

        DEPTH_STENCIL_FORMAT_MISMATCH_PIPELINE_STATE = 615,

        DEPTH_STENCIL_SAMPLE_DESC_MISMATCH_PIPELINE_STATE = 616,

        RENDER_TARGET_NUMBER_MISMATCH_BUNDLE_PIPELINE_STATE = 617,

        RENDER_TARGET_FORMAT_MISMATCH_BUNDLE_PIPELINE_STATE = 618,

        RENDER_TARGET_SAMPLE_DESC_MISMATCH_BUNDLE_PIPELINE_STATE = 619,

        DEPTH_STENCIL_FORMAT_MISMATCH_BUNDLE_PIPELINE_STATE = 620,

        DEPTH_STENCIL_SAMPLE_DESC_MISMATCH_BUNDLE_PIPELINE_STATE = 621,

        CREATESHADER_INVALIDBYTECODE = 622,

        CREATEHEAP_NULLDESC = 623,

        CREATEHEAP_INVALIDSIZE = 624,

        CREATEHEAP_UNRECOGNIZEDHEAPTYPE = 625,

        CREATEHEAP_UNRECOGNIZEDCPUPAGEPROPERTIES = 626,

        CREATEHEAP_UNRECOGNIZEDMEMORYPOOL = 627,

        CREATEHEAP_INVALIDPROPERTIES = 628,

        CREATEHEAP_INVALIDALIGNMENT = 629,

        CREATEHEAP_UNRECOGNIZEDMISCFLAGS = 630,

        CREATEHEAP_INVALIDMISCFLAGS = 631,

        CREATEHEAP_INVALIDARG_RETURN = 632,

        CREATEHEAP_OUTOFMEMORY_RETURN = 633,

        CREATERESOURCEANDHEAP_NULLHEAPPROPERTIES = 634,

        CREATERESOURCEANDHEAP_UNRECOGNIZEDHEAPTYPE = 635,

        CREATERESOURCEANDHEAP_UNRECOGNIZEDCPUPAGEPROPERTIES = 636,

        CREATERESOURCEANDHEAP_UNRECOGNIZEDMEMORYPOOL = 637,

        CREATERESOURCEANDHEAP_INVALIDHEAPPROPERTIES = 638,

        CREATERESOURCEANDHEAP_UNRECOGNIZEDHEAPMISCFLAGS = 639,

        CREATERESOURCEANDHEAP_INVALIDHEAPMISCFLAGS = 640,

        CREATERESOURCEANDHEAP_INVALIDARG_RETURN = 641,

        CREATERESOURCEANDHEAP_OUTOFMEMORY_RETURN = 642,

        GETCUSTOMHEAPPROPERTIES_UNRECOGNIZEDHEAPTYPE = 643,

        GETCUSTOMHEAPPROPERTIES_INVALIDHEAPTYPE = 644,

        CREATE_DESCRIPTOR_HEAP_INVALID_DESC = 645,

        INVALID_DESCRIPTOR_HANDLE = 646,

        CREATERASTERIZERSTATE_INVALID_CONSERVATIVERASTERMODE = 647,

        DEVICE_DRAW_INVALID_SYSTEMVALUE = 648,

        CREATE_CONSTANT_BUFFER_VIEW_INVALID_RESOURCE = 649,

        CREATE_CONSTANT_BUFFER_VIEW_INVALID_DESC = 650,

        CREATE_CONSTANT_BUFFER_VIEW_LARGE_OFFSET = 651,

        CREATE_UNORDEREDACCESS_VIEW_INVALID_COUNTER_USAGE = 652,

        COPY_DESCRIPTORS_INVALID_RANGES = 653,

        COPY_DESCRIPTORS_WRITE_ONLY_DESCRIPTOR = 654,

        CREATEGRAPHICSPIPELINESTATE_RTV_FORMAT_NOT_UNKNOWN = 655,

        CREATEGRAPHICSPIPELINESTATE_INVALID_RENDER_TARGET_COUNT = 656,

        CREATEGRAPHICSPIPELINESTATE_VERTEX_SHADER_NOT_SET = 657,

        CREATEGRAPHICSPIPELINESTATE_INPUTLAYOUT_NOT_SET = 658,

        CREATEGRAPHICSPIPELINESTATE_SHADER_LINKAGE_HS_DS_SIGNATURE_MISMATCH = 659,

        CREATEGRAPHICSPIPELINESTATE_SHADER_LINKAGE_REGISTERINDEX = 660,

        CREATEGRAPHICSPIPELINESTATE_SHADER_LINKAGE_COMPONENTTYPE = 661,

        CREATEGRAPHICSPIPELINESTATE_SHADER_LINKAGE_REGISTERMASK = 662,

        CREATEGRAPHICSPIPELINESTATE_SHADER_LINKAGE_SYSTEMVALUE = 663,

        CREATEGRAPHICSPIPELINESTATE_SHADER_LINKAGE_NEVERWRITTEN_ALWAYSREADS = 664,

        CREATEGRAPHICSPIPELINESTATE_SHADER_LINKAGE_MINPRECISION = 665,

        CREATEGRAPHICSPIPELINESTATE_SHADER_LINKAGE_SEMANTICNAME_NOT_FOUND = 666,

        CREATEGRAPHICSPIPELINESTATE_HS_XOR_DS_MISMATCH = 667,

        CREATEGRAPHICSPIPELINESTATE_HULL_SHADER_INPUT_TOPOLOGY_MISMATCH = 668,

        CREATEGRAPHICSPIPELINESTATE_HS_DS_CONTROL_POINT_COUNT_MISMATCH = 669,

        CREATEGRAPHICSPIPELINESTATE_HS_DS_TESSELLATOR_DOMAIN_MISMATCH = 670,

        CREATEGRAPHICSPIPELINESTATE_INVALID_USE_OF_CENTER_MULTISAMPLE_PATTERN = 671,

        CREATEGRAPHICSPIPELINESTATE_INVALID_USE_OF_FORCED_SAMPLE_COUNT = 672,

        CREATEGRAPHICSPIPELINESTATE_INVALID_PRIMITIVETOPOLOGY = 673,

        CREATEGRAPHICSPIPELINESTATE_INVALID_SYSTEMVALUE = 674,

        CREATEGRAPHICSPIPELINESTATE_OM_DUAL_SOURCE_BLENDING_CAN_ONLY_HAVE_RENDER_TARGET_0 = 675,

        CREATEGRAPHICSPIPELINESTATE_OM_RENDER_TARGET_DOES_NOT_SUPPORT_BLENDING = 676,

        CREATEGRAPHICSPIPELINESTATE_PS_OUTPUT_TYPE_MISMATCH = 677,

        CREATEGRAPHICSPIPELINESTATE_OM_RENDER_TARGET_DOES_NOT_SUPPORT_LOGIC_OPS = 678,

        CREATEGRAPHICSPIPELINESTATE_RENDERTARGETVIEW_NOT_SET = 679,

        CREATEGRAPHICSPIPELINESTATE_DEPTHSTENCILVIEW_NOT_SET = 680,

        CREATEGRAPHICSPIPELINESTATE_GS_INPUT_PRIMITIVE_MISMATCH = 681,

        CREATEGRAPHICSPIPELINESTATE_POSITION_NOT_PRESENT = 682,

        CREATEGRAPHICSPIPELINESTATE_MISSING_ROOT_SIGNATURE_FLAGS = 683,

        CREATEGRAPHICSPIPELINESTATE_INVALID_INDEX_BUFFER_PROPERTIES = 684,

        CREATEGRAPHICSPIPELINESTATE_INVALID_SAMPLE_DESC = 685,

        CREATEGRAPHICSPIPELINESTATE_HS_ROOT_SIGNATURE_MISMATCH = 686,

        CREATEGRAPHICSPIPELINESTATE_DS_ROOT_SIGNATURE_MISMATCH = 687,

        CREATEGRAPHICSPIPELINESTATE_VS_ROOT_SIGNATURE_MISMATCH = 688,

        CREATEGRAPHICSPIPELINESTATE_GS_ROOT_SIGNATURE_MISMATCH = 689,

        CREATEGRAPHICSPIPELINESTATE_PS_ROOT_SIGNATURE_MISMATCH = 690,

        CREATEGRAPHICSPIPELINESTATE_MISSING_ROOT_SIGNATURE = 691,

        EXECUTE_BUNDLE_OPEN_BUNDLE = 692,

        EXECUTE_BUNDLE_DESCRIPTOR_HEAP_MISMATCH = 693,

        EXECUTE_BUNDLE_TYPE = 694,

        DRAW_EMPTY_SCISSOR_RECTANGLE = 695,

        CREATE_ROOT_SIGNATURE_BLOB_NOT_FOUND = 696,

        CREATE_ROOT_SIGNATURE_DESERIALIZE_FAILED = 697,

        CREATE_ROOT_SIGNATURE_INVALID_CONFIGURATION = 698,

        CREATE_ROOT_SIGNATURE_NOT_SUPPORTED_ON_DEVICE = 699,

        CREATERESOURCEANDHEAP_NULLRESOURCEPROPERTIES = 700,

        CREATERESOURCEANDHEAP_NULLHEAP = 701,

        GETRESOURCEALLOCATIONINFO_INVALIDRDESCS = 702,

        MAKERESIDENT_NULLOBJECTARRAY = 703,

        MAKERESIDENT_INVALIDOBJECT = 704,

        EVICT_NULLOBJECTARRAY = 705,

        EVICT_INVALIDOBJECT = 706,

        HEAPS_UNSUPPORTED = 707,

        SET_DESCRIPTOR_TABLE_INVALID = 708,

        SET_ROOT_CONSTANT_INVALID = 709,

        SET_ROOT_CONSTANT_BUFFER_VIEW_INVALID = 710,

        SET_ROOT_SHADER_RESOURCE_VIEW_INVALID = 711,

        SET_ROOT_UNORDERED_ACCESS_VIEW_INVALID = 712,

        SET_VERTEX_BUFFERS_INVALID_DESC = 713,

        SET_VERTEX_BUFFERS_LARGE_OFFSET = 714,

        SET_INDEX_BUFFER_INVALID_DESC = 715,

        SET_INDEX_BUFFER_LARGE_OFFSET = 716,

        SET_STREAM_OUTPUT_BUFFERS_INVALID_DESC = 717,

        CREATERESOURCE_UNRECOGNIZEDDIMENSIONALITY = 718,

        CREATERESOURCE_UNRECOGNIZEDLAYOUT = 719,

        CREATERESOURCE_INVALIDDIMENSIONALITY = 720,

        CREATERESOURCE_INVALIDALIGNMENT = 721,

        CREATERESOURCE_INVALIDMIPLEVELS = 722,

        CREATERESOURCE_INVALIDSAMPLEDESC = 723,

        CREATERESOURCE_INVALIDLAYOUT = 724,

        SET_INDEX_BUFFER_INVALID = 725,

        SET_VERTEX_BUFFERS_INVALID = 726,

        SET_STREAM_OUTPUT_BUFFERS_INVALID = 727,

        SET_RENDER_TARGETS_INVALID = 728,

        CREATEQUERY_HEAP_INVALID_PARAMETERS = 729,

        CREATEQUERY_HEAP_JPEG_NOT_SUPPORTED = 730,

        BEGIN_END_QUERY_INVALID_PARAMETERS = 731,

        CLOSE_COMMAND_LIST_OPEN_QUERY = 732,

        RESOLVE_QUERY_DATA_INVALID_PARAMETERS = 733,

        SET_PREDICATION_INVALID_PARAMETERS = 734,

        TIMESTAMPS_NOT_SUPPORTED = 735,

        UNSTABLE_POWER_STATE = 736,

        CREATERESOURCE_UNRECOGNIZEDFORMAT = 737,

        CREATERESOURCE_INVALIDFORMAT = 738,

        GETCOPYABLELAYOUT_INVALIDSUBRESOURCERANGE = 739,

        GETCOPYABLELAYOUT_INVALIDBASEOFFSET = 740,

        RESOURCE_BARRIER_INVALID_HEAP = 741,

        CREATE_SAMPLER_INVALID = 742,

        CREATECOMMANDSIGNATURE_INVALID = 743,

        EXECUTE_INDIRECT_INVALID_PARAMETERS = 744,

        GETGPUVIRTUALADDRESS_INVALID_RESOURCE_DIMENSION = 745,

        CREATESHADERRESOURCEVIEW_INVALIDPLANEINDEX = 749,

        CREATESHADERRESOURCEVIEW_INVALIDVIDEOPLANEINDEX = 750,

        CREATESHADERRESOURCEVIEW_AMBIGUOUSVIDEOPLANEINDEX = 751,

        CREATERENDERTARGETVIEW_INVALIDPLANEINDEX = 752,

        CREATERENDERTARGETVIEW_INVALIDVIDEOPLANEINDEX = 753,

        CREATERENDERTARGETVIEW_AMBIGUOUSVIDEOPLANEINDEX = 754,

        CREATEUNORDEREDACCESSVIEW_INVALIDPLANEINDEX = 755,

        CREATEUNORDEREDACCESSVIEW_INVALIDVIDEOPLANEINDEX = 756,

        CREATEUNORDEREDACCESSVIEW_AMBIGUOUSVIDEOPLANEINDEX = 757,

        JPEGDECODE_INVALIDSCANDATAOFFSET = 758,

        JPEGDECODE_NOTSUPPORTED = 759,

        JPEGDECODE_DIMENSIONSTOOLARGE = 760,

        JPEGDECODE_INVALIDCOMPONENTS = 761,

        JPEGDECODE_UNSUPPORTEDCOMPONENTS = 762,

        JPEGDECODE_DESTINATIONNOT2D = 763,

        JPEGDECODE_TILEDRESOURCESUNSUPPORTED = 764,

        JPEGDECODE_GUARDRECTSUNSUPPORTED = 765,

        JPEGDECODE_FORMATUNSUPPORTED = 766,

        JPEGDECODE_INVALIDSUBRESOURCE = 767,

        JPEGDECODE_INVALIDMIPLEVEL = 768,

        JPEGDECODE_EMPTYDESTBOX = 769,

        JPEGDECODE_DESTBOXNOT2D = 770,

        JPEGDECODE_DESTBOXNOTSUB = 771,

        JPEGDECODE_DESTBOXESINTERSECT = 772,

        JPEGDECODE_XSUBSAMPLEMISMATCH = 773,

        JPEGDECODE_YSUBSAMPLEMISMATCH = 774,

        JPEGDECODE_XSUBSAMPLEODD = 775,

        JPEGDECODE_YSUBSAMPLEODD = 776,

        JPEGDECODE_UPSCALEUNSUPPORTED = 777,

        JPEGDECODE_TIER4DOWNSCALETOLARGE = 778,

        JPEGDECODE_TIER3DOWNSCALEUNSUPPORTED = 779,

        JPEGDECODE_CHROMASIZEMISMATCH = 780,

        JPEGDECODE_LUMACHROMASIZEMISMATCH = 781,

        JPEGDECODE_INVALIDNUMDESTINATIONS = 782,

        JPEGDECODE_SUBBOXUNSUPPORTED = 783,

        JPEGDECODE_1DESTUNSUPPORTEDFORMAT = 784,

        JPEGDECODE_3DESTUNSUPPORTEDFORMAT = 785,

        JPEGDECODE_SCALEUNSUPPORTED = 786,

        JPEGDECODE_INVALIDSOURCESIZE = 787,

        JPEGDECODE_INVALIDCOPYFLAGS = 788,

        JPEGDECODE_HAZARD = 789,

        JPEGDECODE_UNSUPPORTEDSRCBUFFERUSAGE = 790,

        JPEGDECODE_UNSUPPORTEDSRCBUFFERMISCFLAGS = 791,

        JPEGDECODE_UNSUPPORTEDDSTTEXTUREUSAGE = 792,

        JPEGDECODE_BACKBUFFERNOTSUPPORTED = 793,

        JPEGDECODE_UNSUPPORTEDCOPYFLAGS = 794,

        JPEGENCODE_NOTSUPPORTED = 795,

        JPEGENCODE_INVALIDSCANDATAOFFSET = 796,

        JPEGENCODE_INVALIDCOMPONENTS = 797,

        JPEGENCODE_SOURCENOT2D = 798,

        JPEGENCODE_TILEDRESOURCESUNSUPPORTED = 799,

        JPEGENCODE_GUARDRECTSUNSUPPORTED = 800,

        JPEGENCODE_XSUBSAMPLEMISMATCH = 801,

        JPEGENCODE_YSUBSAMPLEMISMATCH = 802,

        JPEGENCODE_UNSUPPORTEDCOMPONENTS = 803,

        JPEGENCODE_FORMATUNSUPPORTED = 804,

        JPEGENCODE_INVALIDSUBRESOURCE = 805,

        JPEGENCODE_INVALIDMIPLEVEL = 806,

        JPEGENCODE_DIMENSIONSTOOLARGE = 807,

        JPEGENCODE_HAZARD = 808,

        JPEGENCODE_UNSUPPORTEDDSTBUFFERUSAGE = 809,

        JPEGENCODE_UNSUPPORTEDDSTBUFFERMISCFLAGS = 810,

        JPEGENCODE_UNSUPPORTEDSRCTEXTUREUSAGE = 811,

        JPEGENCODE_BACKBUFFERNOTSUPPORTED = 812,

        CREATEQUERYORPREDICATE_UNSUPPORTEDCONTEXTTYPEFORQUERY = 813,

        FLUSH1_INVALIDCONTEXTTYPE = 814,

        CREATERESOURCE_INVALIDCLEARVALUE = 815,

        CREATERESOURCE_UNRECOGNIZEDCLEARVALUEFORMAT = 816,

        CREATERESOURCE_INVALIDCLEARVALUEFORMAT = 817,

        CREATERESOURCE_CLEARVALUEDENORMFLUSH = 818,

        CLEARDEPTHSTENCILVIEW_INVALIDDEPTH = 819,

        CLEARRENDERTARGETVIEW_MISMATCHINGCLEARVALUE = 820,

        CLEARDEPTHSTENCILVIEW_MISMATCHINGCLEARVALUE = 821,

        MAP_INVALIDHEAP = 822,

        UNMAP_INVALIDHEAP = 823,

        MAP_INVALIDRESOURCE = 824,

        UNMAP_INVALIDRESOURCE = 825,

        MAP_INVALIDSUBRESOURCE = 826,

        UNMAP_INVALIDSUBRESOURCE = 827,

        MAP_INVALIDRANGE = 828,

        UNMAP_INVALIDRANGE = 829,

        MAP_NULLRANGE = 830,

        UNMAP_NULLRANGE = 831,

        MAP_INVALIDDATAPOINTER = 832,

        MAP_INVALIDARG_RETURN = 833,

        MAP_OUTOFMEMORY_RETURN = 834,

        EXECUTECOMMANDLISTS_BUNDLENOTSUPPORTED = 835,

        EXECUTECOMMANDLISTS_COMMANDLISTMISMATCH = 836,

        EXECUTECOMMANDLISTS_OPENCOMMANDLIST = 837,

        EXECUTECOMMANDLISTS_FAILEDCOMMANDLIST = 838,

        COPYBUFFERREGION_NULLDST = 839,

        COPYBUFFERREGION_INVALIDDSTRESOURCEDIMENSION = 840,

        COPYBUFFERREGION_DSTRANGEOUTOFBOUNDS = 841,

        COPYBUFFERREGION_NULLSRC = 842,

        COPYBUFFERREGION_INVALIDSRCRESOURCEDIMENSION = 843,

        COPYBUFFERREGION_SRCRANGEOUTOFBOUNDS = 844,

        COPYBUFFERREGION_INVALIDCOPYFLAGS = 845,

        COPYTEXTUREREGION_NULLDST = 846,

        COPYTEXTUREREGION_UNRECOGNIZEDDSTTYPE = 847,

        COPYTEXTUREREGION_INVALIDDSTRESOURCEDIMENSION = 848,

        COPYTEXTUREREGION_INVALIDDSTRESOURCE = 849,

        COPYTEXTUREREGION_INVALIDDSTSUBRESOURCE = 850,

        COPYTEXTUREREGION_INVALIDDSTOFFSET = 851,

        COPYTEXTUREREGION_UNRECOGNIZEDDSTFORMAT = 852,

        COPYTEXTUREREGION_INVALIDDSTFORMAT = 853,

        COPYTEXTUREREGION_INVALIDDSTDIMENSIONS = 854,

        COPYTEXTUREREGION_INVALIDDSTROWPITCH = 855,

        COPYTEXTUREREGION_INVALIDDSTPLACEMENT = 856,

        COPYTEXTUREREGION_INVALIDDSTDSPLACEDFOOTPRINTFORMAT = 857,

        COPYTEXTUREREGION_DSTREGIONOUTOFBOUNDS = 858,

        COPYTEXTUREREGION_NULLSRC = 859,

        COPYTEXTUREREGION_UNRECOGNIZEDSRCTYPE = 860,

        COPYTEXTUREREGION_INVALIDSRCRESOURCEDIMENSION = 861,

        COPYTEXTUREREGION_INVALIDSRCRESOURCE = 862,

        COPYTEXTUREREGION_INVALIDSRCSUBRESOURCE = 863,

        COPYTEXTUREREGION_INVALIDSRCOFFSET = 864,

        COPYTEXTUREREGION_UNRECOGNIZEDSRCFORMAT = 865,

        COPYTEXTUREREGION_INVALIDSRCFORMAT = 866,

        COPYTEXTUREREGION_INVALIDSRCDIMENSIONS = 867,

        COPYTEXTUREREGION_INVALIDSRCROWPITCH = 868,

        COPYTEXTUREREGION_INVALIDSRCPLACEMENT = 869,

        COPYTEXTUREREGION_INVALIDSRCDSPLACEDFOOTPRINTFORMAT = 870,

        COPYTEXTUREREGION_SRCREGIONOUTOFBOUNDS = 871,

        COPYTEXTUREREGION_INVALIDDSTCOORDINATES = 872,

        COPYTEXTUREREGION_INVALIDSRCBOX = 873,

        COPYTEXTUREREGION_FORMATMISMATCH = 874,

        COPYTEXTUREREGION_EMPTYBOX = 875,

        COPYTEXTUREREGION_INVALIDCOPYFLAGS = 876,

        RESOLVESUBRESOURCE_INVALID_SUBRESOURCE_INDEX = 877,

        RESOLVESUBRESOURCE_INVALID_FORMAT = 878,

        RESOLVESUBRESOURCE_RESOURCE_MISMATCH = 879,

        RESOLVESUBRESOURCE_INVALID_SAMPLE_COUNT = 880,

        CREATECOMPUTEPIPELINESTATE_INVALID_SHADER = 881,

        CREATECOMPUTEPIPELINESTATE_CS_ROOT_SIGNATURE_MISMATCH = 882,

        CREATECOMPUTEPIPELINESTATE_MISSING_ROOT_SIGNATURE = 883,

        CREATEPIPELINESTATE_INVALIDCACHEDBLOB = 884,

        CREATEPIPELINESTATE_CACHEDBLOBADAPTERMISMATCH = 885,

        CREATEPIPELINESTATE_CACHEDBLOBDRIVERVERSIONMISMATCH = 886,

        CREATEPIPELINESTATE_CACHEDBLOBDESCMISMATCH = 887,

        CREATEPIPELINESTATE_CACHEDBLOBIGNORED = 888,

        WRITETOSUBRESOURCE_INVALIDHEAP = 889,

        WRITETOSUBRESOURCE_INVALIDRESOURCE = 890,

        WRITETOSUBRESOURCE_INVALIDBOX = 891,

        WRITETOSUBRESOURCE_INVALIDSUBRESOURCE = 892,

        WRITETOSUBRESOURCE_EMPTYBOX = 893,

        READFROMSUBRESOURCE_INVALIDHEAP = 894,

        READFROMSUBRESOURCE_INVALIDRESOURCE = 895,

        READFROMSUBRESOURCE_INVALIDBOX = 896,

        READFROMSUBRESOURCE_INVALIDSUBRESOURCE = 897,

        READFROMSUBRESOURCE_EMPTYBOX = 898,

        TOO_MANY_NODES_SPECIFIED = 899,

        INVALID_NODE_INDEX = 900,

        GETHEAPPROPERTIES_INVALIDRESOURCE = 901,

        NODE_MASK_MISMATCH = 902,

        COMMAND_LIST_OUTOFMEMORY = 903,

        COMMAND_LIST_MULTIPLE_SWAPCHAIN_BUFFER_REFERENCES = 904,

        COMMAND_LIST_TOO_MANY_SWAPCHAIN_REFERENCES = 905,

        COMMAND_QUEUE_TOO_MANY_SWAPCHAIN_REFERENCES = 906,

        EXECUTECOMMANDLISTS_WRONGSWAPCHAINBUFFERREFERENCE = 907,

        COMMAND_LIST_SETRENDERTARGETS_INVALIDNUMRENDERTARGETS = 908,

        CREATE_QUEUE_INVALID_TYPE = 909,

        CREATE_QUEUE_INVALID_FLAGS = 910,

        CREATESHAREDRESOURCE_INVALIDFLAGS = 911,

        CREATESHAREDRESOURCE_INVALIDFORMAT = 912,

        CREATESHAREDHEAP_INVALIDFLAGS = 913,

        REFLECTSHAREDPROPERTIES_UNRECOGNIZEDPROPERTIES = 914,

        REFLECTSHAREDPROPERTIES_INVALIDSIZE = 915,

        REFLECTSHAREDPROPERTIES_INVALIDOBJECT = 916,

        KEYEDMUTEX_INVALIDOBJECT = 917,

        KEYEDMUTEX_INVALIDKEY = 918,

        KEYEDMUTEX_WRONGSTATE = 919,

        CREATE_QUEUE_INVALID_PRIORITY = 920,

        OBJECT_DELETED_WHILE_STILL_IN_USE = 921,

        CREATEPIPELINESTATE_INVALID_FLAGS = 922,

        HEAP_ADDRESS_RANGE_HAS_NO_RESOURCE = 923,

        COMMAND_LIST_DRAW_RENDER_TARGET_DELETED = 924,

        CREATEGRAPHICSPIPELINESTATE_ALL_RENDER_TARGETS_HAVE_UNKNOWN_FORMAT = 925,

        HEAP_ADDRESS_RANGE_INTERSECTS_MULTIPLE_BUFFERS = 926,

        EXECUTECOMMANDLISTS_GPU_WRITTEN_READBACK_RESOURCE_MAPPED = 927,

        UNMAP_RANGE_NOT_NEEDED = 928,

        UNMAP_RANGE_NOT_EMPTY = 929,

        MAP_INVALID_NULLRANGE = 930,

        UNMAP_INVALID_NULLRANGE = 931,

        NO_GRAPHICS_API_SUPPORT = 932,

        NO_COMPUTE_API_SUPPORT = 933,

        RESOLVESUBRESOURCE_RESOURCE_FLAGS_NOT_SUPPORTED = 934,

        GPU_BASED_VALIDATION_ROOT_ARGUMENT_UNINITIALIZED = 935,

        GPU_BASED_VALIDATION_DESCRIPTOR_HEAP_INDEX_OUT_OF_BOUNDS = 936,

        GPU_BASED_VALIDATION_DESCRIPTOR_TABLE_REGISTER_INDEX_OUT_OF_BOUNDS = 937,

        GPU_BASED_VALIDATION_DESCRIPTOR_UNINITIALIZED = 938,

        GPU_BASED_VALIDATION_DESCRIPTOR_TYPE_MISMATCH = 939,

        GPU_BASED_VALIDATION_SRV_RESOURCE_DIMENSION_MISMATCH = 940,

        GPU_BASED_VALIDATION_UAV_RESOURCE_DIMENSION_MISMATCH = 941,

        GPU_BASED_VALIDATION_INCOMPATIBLE_RESOURCE_STATE = 942,

        COPYRESOURCE_NULLDST = 943,

        COPYRESOURCE_INVALIDDSTRESOURCE = 944,

        COPYRESOURCE_NULLSRC = 945,

        COPYRESOURCE_INVALIDSRCRESOURCE = 946,

        RESOLVESUBRESOURCE_NULLDST = 947,

        RESOLVESUBRESOURCE_INVALIDDSTRESOURCE = 948,

        RESOLVESUBRESOURCE_NULLSRC = 949,

        RESOLVESUBRESOURCE_INVALIDSRCRESOURCE = 950,

        PIPELINE_STATE_TYPE_MISMATCH = 951,

        COMMAND_LIST_DISPATCH_ROOT_SIGNATURE_NOT_SET = 952,

        COMMAND_LIST_DISPATCH_ROOT_SIGNATURE_MISMATCH = 953,

        RESOURCE_BARRIER_ZERO_BARRIERS = 954,

        BEGIN_END_EVENT_MISMATCH = 955,

        RESOURCE_BARRIER_POSSIBLE_BEFORE_AFTER_MISMATCH = 956,

        RESOURCE_BARRIER_MISMATCHING_BEGIN_END = 957,

        GPU_BASED_VALIDATION_INVALID_RESOURCE = 958,

        USE_OF_ZERO_REFCOUNT_OBJECT = 959,

        OBJECT_EVICTED_WHILE_STILL_IN_USE = 960,

        GPU_BASED_VALIDATION_ROOT_DESCRIPTOR_ACCESS_OUT_OF_BOUNDS = 961,

        CREATEPIPELINELIBRARY_INVALIDLIBRARYBLOB = 962,

        CREATEPIPELINELIBRARY_DRIVERVERSIONMISMATCH = 963,

        CREATEPIPELINELIBRARY_ADAPTERVERSIONMISMATCH = 964,

        CREATEPIPELINELIBRARY_UNSUPPORTED = 965,

        CREATE_PIPELINELIBRARY = 966,

        LIVE_PIPELINELIBRARY = 967,

        DESTROY_PIPELINELIBRARY = 968,

        STOREPIPELINE_NONAME = 969,

        STOREPIPELINE_DUPLICATENAME = 970,

        LOADPIPELINE_NAMENOTFOUND = 971,

        LOADPIPELINE_INVALIDDESC = 972,

        PIPELINELIBRARY_SERIALIZE_NOTENOUGHMEMORY = 973,

        CREATEGRAPHICSPIPELINESTATE_PS_OUTPUT_RT_OUTPUT_MISMATCH = 974,

        SETEVENTONMULTIPLEFENCECOMPLETION_INVALIDFLAGS = 975,

        CREATE_QUEUE_VIDEO_NOT_SUPPORTED = 976,

        CREATE_COMMAND_ALLOCATOR_VIDEO_NOT_SUPPORTED = 977,

        CREATEQUERY_HEAP_VIDEO_DECODE_STATISTICS_NOT_SUPPORTED = 978,

        CREATE_VIDEODECODECOMMANDLIST = 979,

        CREATE_VIDEODECODER = 980,

        CREATE_VIDEODECODESTREAM = 981,

        LIVE_VIDEODECODECOMMANDLIST = 982,

        LIVE_VIDEODECODER = 983,

        LIVE_VIDEODECODESTREAM = 984,

        DESTROY_VIDEODECODECOMMANDLIST = 985,

        DESTROY_VIDEODECODER = 986,

        DESTROY_VIDEODECODESTREAM = 987,

        DECODE_FRAME_INVALID_PARAMETERS = 988,

        DEPRECATED_API = 989,

        RESOURCE_BARRIER_MISMATCHING_COMMAND_LIST_TYPE = 990,

        COMMAND_LIST_DESCRIPTOR_TABLE_NOT_SET = 991,

        COMMAND_LIST_ROOT_CONSTANT_BUFFER_VIEW_NOT_SET = 992,

        COMMAND_LIST_ROOT_SHADER_RESOURCE_VIEW_NOT_SET = 993,

        COMMAND_LIST_ROOT_UNORDERED_ACCESS_VIEW_NOT_SET = 994,

        DISCARD_INVALID_SUBRESOURCE_RANGE = 995,

        DISCARD_ONE_SUBRESOURCE_FOR_MIPS_WITH_RECTS = 996,

        DISCARD_NO_RECTS_FOR_NON_TEXTURE2D = 997,

        COPY_ON_SAME_SUBRESOURCE = 998,

        SETRESIDENCYPRIORITY_INVALID_PAGEABLE = 999,

        GPU_BASED_VALIDATION_UNSUPPORTED = 1000,

        STATIC_DESCRIPTOR_INVALID_DESCRIPTOR_CHANGE = 1001,

        DATA_STATIC_DESCRIPTOR_INVALID_DATA_CHANGE = 1002,

        DATA_STATIC_WHILE_SET_AT_EXECUTE_DESCRIPTOR_INVALID_DATA_CHANGE = 1003,

        EXECUTE_BUNDLE_STATIC_DESCRIPTOR_DATA_STATIC_NOT_SET = 1004,

        GPU_BASED_VALIDATION_RESOURCE_ACCESS_OUT_OF_BOUNDS = 1005,

        GPU_BASED_VALIDATION_SAMPLER_MODE_MISMATCH = 1006,

        CREATE_FENCE_INVALID_FLAGS = 1007,

        RESOURCE_BARRIER_DUPLICATE_SUBRESOURCE_TRANSITIONS = 1008,

        SETRESIDENCYPRIORITY_INVALID_PRIORITY = 1009,

        CREATE_PASS = 1010,

        DESTROY_PASS = 1011,

        LIVE_PASS = 1012,

        CREATE_DESCRIPTOR_HEAP_LARGE_NUM_DESCRIPTORS = 1013,

        BEGIN_EVENT = 1014,

        END_EVENT = 1015,

        CREATEDEVICE_DEBUG_LAYER_STARTUP_OPTIONS = 1016,

        CREATEDEPTHSTENCILSTATE_DEPTHBOUNDSTEST_UNSUPPORTED = 1017,

        CREATEPIPELINESTATE_DUPLICATE_SUBOBJECT = 1018,

        CREATEPIPELINESTATE_UNKNOWN_SUBOBJECT = 1019,

        CREATEPIPELINESTATE_ZERO_SIZE_STREAM = 1020,

        CREATEPIPELINESTATE_INVALID_STREAM = 1021,

        CREATEPIPELINESTATE_CANNOT_DEDUCE_TYPE = 1022,

        COMMAND_LIST_STATIC_DESCRIPTOR_RESOURCE_DIMENSION_MISMATCH = 1023,

        CREATE_COMMAND_QUEUE_INSUFFICIENT_PRIVILEGE_FOR_GLOBAL_REALTIME = 1024,

        CREATE_COMMAND_QUEUE_INSUFFICIENT_HARDWARE_SUPPORT_FOR_GLOBAL_REALTIME = 1025,

        ATOMICCOPYBUFFER_INVALID_ARCHITECTURE = 1026,

        ATOMICCOPYBUFFER_NULL_DST = 1027,

        ATOMICCOPYBUFFER_INVALID_DST_RESOURCE_DIMENSION = 1028,

        ATOMICCOPYBUFFER_DST_RANGE_OUT_OF_BOUNDS = 1029,

        ATOMICCOPYBUFFER_NULL_SRC = 1030,

        ATOMICCOPYBUFFER_INVALID_SRC_RESOURCE_DIMENSION = 1031,

        ATOMICCOPYBUFFER_SRC_RANGE_OUT_OF_BOUNDS = 1032,

        ATOMICCOPYBUFFER_INVALID_OFFSET_ALIGNMENT = 1033,

        ATOMICCOPYBUFFER_NULL_DEPENDENT_RESOURCES = 1034,

        ATOMICCOPYBUFFER_NULL_DEPENDENT_SUBRESOURCE_RANGES = 1035,

        ATOMICCOPYBUFFER_INVALID_DEPENDENT_RESOURCE = 1036,

        ATOMICCOPYBUFFER_INVALID_DEPENDENT_SUBRESOURCE_RANGE = 1037,

        ATOMICCOPYBUFFER_DEPENDENT_SUBRESOURCE_OUT_OF_BOUNDS = 1038,

        ATOMICCOPYBUFFER_DEPENDENT_RANGE_OUT_OF_BOUNDS = 1039,

        ATOMICCOPYBUFFER_ZERO_DEPENDENCIES = 1040,

        DEVICE_CREATE_SHARED_HANDLE_INVALIDARG = 1041,

        DESCRIPTOR_HANDLE_WITH_INVALID_RESOURCE = 1042,

        SETDEPTHBOUNDS_INVALIDARGS = 1043,

        GPU_BASED_VALIDATION_RESOURCE_STATE_IMPRECISE = 1044,

        COMMAND_LIST_PIPELINE_STATE_NOT_SET = 1045,

        CREATEGRAPHICSPIPELINESTATE_SHADER_MODEL_MISMATCH = 1046,

        OBJECT_ACCESSED_WHILE_STILL_IN_USE = 1047,

        PROGRAMMABLE_MSAA_UNSUPPORTED = 1048,

        SETSAMPLEPOSITIONS_INVALIDARGS = 1049,

        RESOLVESUBRESOURCEREGION_INVALID_RECT = 1050,

        CREATE_VIDEODECODECOMMANDQUEUE = 1051,

        CREATE_VIDEOPROCESSCOMMANDLIST = 1052,

        CREATE_VIDEOPROCESSCOMMANDQUEUE = 1053,

        LIVE_VIDEODECODECOMMANDQUEUE = 1054,

        LIVE_VIDEOPROCESSCOMMANDLIST = 1055,

        LIVE_VIDEOPROCESSCOMMANDQUEUE = 1056,

        DESTROY_VIDEODECODECOMMANDQUEUE = 1057,

        DESTROY_VIDEOPROCESSCOMMANDLIST = 1058,

        DESTROY_VIDEOPROCESSCOMMANDQUEUE = 1059,

        CREATE_VIDEOPROCESSOR = 1060,

        CREATE_VIDEOPROCESSSTREAM = 1061,

        LIVE_VIDEOPROCESSOR = 1062,

        LIVE_VIDEOPROCESSSTREAM = 1063,

        DESTROY_VIDEOPROCESSOR = 1064,

        DESTROY_VIDEOPROCESSSTREAM = 1065,

        PROCESS_FRAME_INVALID_PARAMETERS = 1066,

        COPY_INVALIDLAYOUT = 1067,

        D3D12_MESSAGES_END = 1068
    }
}
