// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License MIT. See License.md in the repository root for more information.

// Ported from um\d3d12.h in the Windows SDK for Windows 10.0.15063.0
// Original source is Copyright © Microsoft. All rights reserved.

namespace TerraFX.Interop
{
    public enum D3D12_FILTER
    {
       MIN_MAG_MIP_POINT = 0,

       MIN_MAG_POINT_MIP_LINEAR = 1,

       MIN_POINT_MAG_LINEAR_MIP_POINT = 4,

       MIN_POINT_MAG_MIP_LINEAR = 5,

       MIN_LINEAR_MAG_MIP_POINT = 16,

       MIN_LINEAR_MAG_POINT_MIP_LINEAR = 17,

       MIN_MAG_LINEAR_MIP_POINT = 20,

       MIN_MAG_MIP_LINEAR = 21,

       ANISOTROPIC = 85,

       COMPARISON_MIN_MAG_MIP_POINT = 128,

       COMPARISON_MIN_MAG_POINT_MIP_LINEAR = 129,

       COMPARISON_MIN_POINT_MAG_LINEAR_MIP_POINT = 132,

       COMPARISON_MIN_POINT_MAG_MIP_LINEAR = 133,

       COMPARISON_MIN_LINEAR_MAG_MIP_POINT = 144,

       COMPARISON_MIN_LINEAR_MAG_POINT_MIP_LINEAR = 145,

       COMPARISON_MIN_MAG_LINEAR_MIP_POINT = 148,

       COMPARISON_MIN_MAG_MIP_LINEAR = 149,

       COMPARISON_ANISOTROPIC = 213,

       MINIMUM_MIN_MAG_MIP_POINT = 256,

       MINIMUM_MIN_MAG_POINT_MIP_LINEAR = 257,

       MINIMUM_MIN_POINT_MAG_LINEAR_MIP_POINT = 260,

       MINIMUM_MIN_POINT_MAG_MIP_LINEAR = 261,

       MINIMUM_MIN_LINEAR_MAG_MIP_POINT = 272,

       MINIMUM_MIN_LINEAR_MAG_POINT_MIP_LINEAR = 273,

       MINIMUM_MIN_MAG_LINEAR_MIP_POINT = 276,

       MINIMUM_MIN_MAG_MIP_LINEAR = 277,

       MINIMUM_ANISOTROPIC = 341,

       MAXIMUM_MIN_MAG_MIP_POINT = 384,

       MAXIMUM_MIN_MAG_POINT_MIP_LINEAR = 385,

       MAXIMUM_MIN_POINT_MAG_LINEAR_MIP_POINT = 388,

       MAXIMUM_MIN_POINT_MAG_MIP_LINEAR = 389,

       MAXIMUM_MIN_LINEAR_MAG_MIP_POINT = 400,

       MAXIMUM_MIN_LINEAR_MAG_POINT_MIP_LINEAR = 401,

       MAXIMUM_MIN_MAG_LINEAR_MIP_POINT = 404,

       MAXIMUM_MIN_MAG_MIP_LINEAR = 405,

       MAXIMUM_ANISOTROPIC = 469
    }
}
